### ISSUE TITLE
header tags bold

### ISSUE THREAD

**Issue by rimmesbe** [dbasen4/prj-rev-bwfs-dasmoto#5]
Header tags (h1, h2, h3...) default to bold, so no need to add it.

https://github.com/dbasen4/prj-rev-bwfs-dasmoto/blob/master/DevProject/resources/css/index.css#L4

**Comment by dbasen4** [comment]
Good to know! If I were to add in italics to a header tag, would it stay bold and just add italics? Or would I need to add it in order to have a bold/italic header?
